#启动端口
server:
  port: 8088
#  servlet:
#    context-path: /backend
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://1.94.0.129:3306/diancan?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Scl123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: diancan-webapp
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    serialization:
#      write-dates-as-timestamps: false
#日志配置
logging:
  level:
    root: info
    com.ycc: debug
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(39579){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint}%L %m%n%wEx'
  file:
#    name: diancan.log
    path: /data/logs
  rollingpolicy:
    file:
      max-history: 7
      clean-history-on-start: true
      filename-pattern: "/data/logs/diancan-%d{yyyy-MM-dd}.%i.log"
#自动建表设置
mybatis:
  table:
    #create系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据;
    #update系统会自动判断哪些表是新建的．哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据;
    #add新增表/新增字段/新增索引新增唯一约束的功能，不做做修改和删除(只在版本1.0.9.RELEASE及以上支持);
    #none系统不做任何处理;
    auto: add
  model:
    #扫描用于创建表的对象的包名
    pack: com.ycc.diancan.definition
  database:
    #数据库类型目前只支持mysql
    type: mysql
#mybaties配置
mybatis-plus:
  #固定的
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


